README.md, assets/js/helpers/getUrlHostName.js
Character case matters. 
Change getUrlHost**n**ame to getUrlHost**N**ame.
=> Corrects file name and updates the installation description 

.github/workflows/deploy.yml
Pour configurer cette action, il faut adapter les secrets:
```
RSYNC_KNOWN_HOSTS
RSYNC_PRIVATE_SSH_KEY
RSYNC_REMOTE_FOLDER
RSYNC_REMOTE_HOST
RSYNC_REMOTE_PORT
RSYNC_REMOTE_USER
```
=> ✨ feat(action): Init deploy github action

assets/js/components/SiteAnalysisResult.js, assets/js/services/AnalysisService.js, assets/js/services/ApiService.js, assets/js/services/ResultCacheService.js
+ avoid showing the modal dialog when requesting by id (see `options.silent`)
=> Fix ecoindex analysis by id

.github/workflows/deploy.yml
=> 🐛 fix(ci): Remove hugo minify in deploy action

assets/js/components/ResultRangeSlider.js, assets/js/components/SiteAnalysisResult.js, content/fr/result/index.md
=> Fix result slider scores display

.github/workflows/deploy.yml
=> ♻️ refact(deploy): Update deploy github action to trigger tag semver

layouts/partials/widgets/result-empreinte.html
* Updates external link address.
* Fixes title and icon.
=> Partially solves issue #136

package-lock.json, package.json
"@fullhuman/postcss-purgecss": "^5.0.0"
"autoprefixer": "^10.4.12"
"purgecss": "^5.0"
"postcss-cli": "^10.0.0"
"postcss-simple-vars": "^7.0"
=> ⬆️ chore(deps): Update deps

assets/js/components/SiteAnalysisResult.js, content/fr/result/index.md
=> Fix footprint analysis result display with corresponding unit

.github/dependabot.yml, .github/workflows/deploy.yml, .github/workflows/quality.yml
Lorsque l'on ouvre une PR.
Également, ajout d'une configuration dependabot pour vérifier les mises à jour des actions
=> 👷 ci(githubaction): Ajout d'une validation des dépendances

assets/js/helpers/urlUtils.js
Ajout de la vérification **côté client** du type de ressource soumise pour analyse par les utilisateurs.
Se référer à l'issue #142.
=> Prevents incorrect resource submission (issue #142)

assets/js/services/AnalysisService.js
Catch error in rejected promises
Fixes infinite pending modal on timeout
=> Fix error handling

layouts/shortcodes/ecoindex_form.html
Resolve issue #200 ?
URL tested with success : 
- google.com
- http://google.com
- www.google.com
- https://www.google.com
=> Remove URL field type to accept uncomplete URL

.github/workflows/stale.yml
=> ci: add github actions stale

content/en/result/_45_what-it-means.md, i18n/en.toml, i18n/fr.toml
=> docs: fix convertion of co2 emissions with car distance

assets/js/index.js
=> fix: multilingual redirect on URL testing from the result page

assets/js/services/ApiService.js, config/_default/params.toml
=> Revert "Feat/env variables"

assets/js/services/ApiService.js
Hello @vvatelot ! 
This should fix the 307 redirect error.
=> fix(api): add ending slash to prevent 307 redirect

layouts/partials/footer.html
=> doc: Update link of greenit.fr association in footer

assets/js/services/ApiService.js
This way, the client retry to get result until 10minutes
=> fix(api): Remove timeout and set retry limit to 300
